### PR TITLE
feat: add `order` variable to `coder_app` modules

### PR DESCRIPTION
**Pull request by michaelbrewer**
Add per the coder docs coder applications can be reordered in the ui via the order field

https://coder.com/docs/v2/latest/templates/resource-ordering#applications

This change allows this:

```hcl
module "code-server" {
  source          = "registry.coder.com/modules/code-server/coder"
  version         = "1.0.5"
  agent_id        = coder_agent.main.id
  install_version = "4.8.3"
  order           = 2
}

module "filebrowser" {
  source   = "registry.coder.com/modules/filebrowser/coder"
  version  = "1.0.3"
  agent_id = coder_agent.example.id
  folder   = "/home/coder/project"
  order    = 1
}
```

See issue #178

### CODE REVIEW

**Review by matifali — COMMENTED** [review]
Thank you @michaelbrewer. Great contribution. We recently added this functionality so it will only work on deployments on latest release. 
We are still looking for a suitable way to check Coder version compatibility with modules that depend on newer features. 
See #121

**Comment by michaelbrewer** [comment]
@matifali  can we bump the required provider to "0.14.2" when order was added ?

``hcl
terraform {
  required_version = ">= 1.0"
  required_providers {
    coder = {
      source  = "coder/coder"
      version = ">= 0.14.2"
    }
  }
}
```

**Comment by michaelbrewer** [comment]
@matifali set the required version for `coder/coder`  to be >= 0.14.2

**Review by matifali — APPROVED** [review]

**Review by matifali — APPROVED** [review]
LGTM. Waiting for an approval from @mtojek and then we are good to merge.

**Review by mtojek — APPROVED** [review]
👍 

Thanks for working on this! Should we use the latest version of coder provider?

**Comment by michaelbrewer** [comment]
@mtojek - So, i can change the required version to `0.18.0` if needed, i just used `0.14.2` as this was when `order` was added to `coder_app`.

**Comment by mtojek** [comment]
I see 👍 I think the last `order` change was introduced in `v0.17.0`, so maybe just bump it to this version.

**Comment by michaelbrewer** [comment]
Cool @mtojek  updated.

**Pull request merged**
