### PR TITLE
chore: fmt

### PR DESCRIPTION
**Pull request by matifali**

### CODE REVIEW

**Review by stirby — COMMENTED** [review]
Looks good.

**Comment by matifali** [comment]
Can you also approve?

**Review by stirby — APPROVED** [review]
Good to merge.

**Comment by matifali** [comment]
### Merge Activity

* **Oct 4, 12:39 AM**: @matifali started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/coder/modules/73).

**Pull request merged**
