### PR TITLE
feat(git-config): allow `data.coder_workspace.me.owner_email` to be blank

### LINKED ISSUE #162: Git config 1.0.3 Call to function "coalesce" failed: no non-null, non-empty-string arguments.
I updated the `git-config` module to `1.0.3` today and get this error on running `coder templates push...`:
```
2024-02-15 01:12:29.175Z Error: Error in function call
2024-02-15 01:12:29.175Z on .terraform/modules/git-config/main.tf line 67, in resource "coder_env" "git_author_email":
2024-02-15 01:12:29.175Z   67:   value    = coalesce(try(data.coder_parameter.user_email[0].value, ""), data.coder_workspace.me.owner_email)
2024-02-15 01:12:29.175Z     ├────────────────
2024-02-15 01:12:29.175Z     │ data.coder_parameter.user_email is empty tuple
2024-02-15 01:12:29.175Z     │ data.coder_workspace.me.owner_email is ""
2024-02-15 01:12:29.175Z 
2024-02-15 01:12:29.175Z Call to function "coalesce" failed: no non-null, non-empty-string arguments.
2024-02-15 01:12:29.175Z Error: Error in function call
2024-02-15 01:12:29.175Z on .terraform/modules/git-config/main.tf line 73, in resource "coder_env" "git_commmiter_email":
2024-02-15 01:12:29.175Z   73:   value    = coalesce(try(data.coder_parameter.user_email[0].value, ""), data.coder_workspace.me.owner_email)
2024-02-15 01:12:29.175Z     ├────────────────
2024-02-15 01:12:29.175Z     │ data.coder_parameter.user_email is empty tuple
2024-02-15 01:12:29.175Z     │ data.coder_workspace.me.owner_email is ""
2024-02-15 01:12:29.175Z 
2024-02-15 01:12:29.175Z Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```

I use the module like this:
```tf
module "git-config" {
  source                = "registry.coder.com/modules/git-config/coder"
  version               = "1.0.3"
  agent_id              = coder_agent.main.id
  allow_username_change = false
}
```

It seems this PR is related: #141

Edit:
When reverting the version to 1.0.2 for this module, everything seems to work

### PR DESCRIPTION
**Pull request by michaelbrewer**
closes #162

### CODE REVIEW

**Comment by matifali** [comment]
@michaelbrewer I think we should fix it on the provider side. I just submitted https://github.com/coder/terraform-provider-coder/pull/209 which should resolve the issue.

**Comment by michaelbrewer** [comment]
Yes. That would fix it for module like this.

**Comment by michaelbrewer** [comment]
@matifali - once the provider update is available I can change this to just be the tests :).

**Review by matifali — APPROVED** [review]

**Comment by matifali** [comment]
Merging this won't disturb any existing behavior.

**Comment by michaelbrewer** [comment]
> @matifali - once the provider update is available I can change this to just be the tests :).

PR #254

**Pull request merged**
