### PR TITLE
added azure region module

### PR DESCRIPTION
**Pull request by stirby**
Added module for azure regions

### CODE REVIEW

**Review by matifali — APPROVED** [review]
LGTM. Nice. Have you tested this?

**Comment by stirby** [comment]
> LGTM. Nice. Have you tested this?

I have not; I assume I can deploy to vercel from my branch? I have the main branch testing URL

**Comment by matifali** [comment]
@stirby, you can test by using the source URL of the form,
`source = "git::https://github.com/<USERNAME>/<REPO>.git//<FOLDER>?ref=<BRANCH>"`

Which in your case will be
`source = "git::https://github.com/coder/modules.git//azure-region?ref=steve-regions"`

**Comment by stirby** [comment]
@matifali Thank you for the help.

Tested, fixed the issues.

**Pull request merged**
