### PR TITLE
fix(code-server): set `settings` variable type to `any`

### LINKED ISSUE #296: bug(code-server): Inability to set object values in `settings`
[Discord Thread](https://discord.com/channels/747933592273027093/1287083320949080125)

---

The type of the [`settings` variable](https://github.com/coder/modules/blob/93c4fb3a8df4add1ca9e82897e26b6e207291c1b/code-server/main.tf#L41-L45) is `map(string)` and therefore does not allow you to set settings like [`files.exclude`](https://stackoverflow.com/a/33277809) which takes in an object.

You would want to set the value like this, but the type doesn't allow you to do so.
```
settings = {
    "files.exclude" = {
      "**/.*": true
    },
    "workbench.colorTheme" = "Default Dark Modern"
}
```

I think all that has to be done is set the variable's type to `map(any)`.

### PR DESCRIPTION
**Pull request by phorcys420**
```tf
module "code-server" {
  source = "git::https://github.com/coder/modules.git//code-server?ref=phorcys/code-server-settings-fix"

  settings = {
    "workbench.colorTheme" = "Dracula",
    "test.test" = ["hi"],
    "test.test2" = {
      "hello" = "hi"
    }
  }

  agent_id                = coder_agent.dev.id
}
```

image

Closes #296

### CODE REVIEW

**Comment by matifali** [comment]
@phorcys420 Can you also do it for `vscode-web`?

**Comment by phorcys420** [comment]
@matifali yes, i will make a separate PR

**Comment by phorcys420** [comment]
tested on https://dev.coder.com/templates/coder/coder-copy2/versions/adoring_fermi0

**Comment by matifali** [comment]
@phorcys420 Have you seen: https://developer.hashicorp.com/terraform/language/expressions/type-constraints#dynamic-types-the-any-constraint

I think it is fine to use `any` for this use case.

**Review by matifali — APPROVED** [review]
LGTM. Have you verified that it now solves the issue?

**Comment by 9techijcore** [comment]
Hello,
Latest release is still v1.0.25, is it possible for you to trigger a new release so we can use this ?
Thanks in advance !

**Comment by matifali** [comment]
@9techijcore I am waiting for #369 and we will cut a release.

**Comment by matifali** [comment]
v1.0.26 has been pushed.

**Pull request merged**
